// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pedidos_dap5.Models;

#nullable disable

namespace pedidosdap5.Migrations
{
    [DbContext(typeof(PedidosContext))]
    [Migration("20221228121719_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pedidos_dap5.Models.Estado", b =>
                {
                    b.Property<int>("Idestado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idestado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idestado"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Idestado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("pedidos_dap5.Models.Grado", b =>
                {
                    b.Property<int>("IdGrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idGrado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrado"));

                    b.Property<string>("Grado1")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("Grado");

                    b.HasKey("IdGrado");

                    b.ToTable("Grados");
                });

            modelBuilder.Entity("pedidos_dap5.Models.Pedido", b =>
                {
                    b.Property<int>("Idpedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idpedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idpedido"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_inicio");

                    b.Property<int?>("Tecnico")
                        .HasColumnType("int")
                        .HasColumnName("tecnico");

                    b.Property<int>("Usuario")
                        .HasColumnType("int")
                        .HasColumnName("usuario");

                    b.HasKey("Idpedido")
                        .HasName("PK_pedidos");

                    b.HasIndex("Estado");

                    b.HasIndex("Tecnico");

                    b.HasIndex("Usuario");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("pedidos_dap5.Models.Solucione", b =>
                {
                    b.Property<int>("Idsolucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idsolucion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idsolucion"));

                    b.Property<DateTime?>("FechaSolucion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_solucion");

                    b.Property<int>("Idpedido")
                        .HasColumnType("int")
                        .HasColumnName("idpedido");

                    b.Property<string>("Solucion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("solucion");

                    b.Property<int?>("Tecnico")
                        .HasColumnType("int")
                        .HasColumnName("tecnico");

                    b.HasKey("Idsolucion")
                        .HasName("PK_soluciones");

                    b.HasIndex("Idpedido");

                    b.HasIndex("Tecnico");

                    b.ToTable("Soluciones");
                });

            modelBuilder.Entity("pedidos_dap5.Models.Tecnico", b =>
                {
                    b.Property<int>("Idtecnico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idtecnico");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idtecnico"));

                    b.Property<string>("CuentaRina")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cuenta_rina");

                    b.Property<string>("Interno")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("interno");

                    b.Property<string>("Tecnico1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tecnico");

                    b.HasKey("Idtecnico")
                        .HasName("PK_tecnicos");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("pedidos_dap5.Models.Usuario", b =>
                {
                    b.Property<int>("Idusuaio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idusuaio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idusuaio"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("Grado")
                        .HasColumnType("int")
                        .HasColumnName("grado");

                    b.Property<string>("Interno")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("TelParticular")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tel_particular");

                    b.Property<string>("Usuario1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("usuario");

                    b.HasKey("Idusuaio")
                        .HasName("PK_usuarios");

                    b.HasIndex("Grado");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("pedidos_dap5.Models.ViewModels.ViewModelPedido", b =>
                {
                    b.Property<int>("Idpedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idpedido"));

                    b.Property<string>("Descripcion_estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion_pedido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaInicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tecnico1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idpedido");

                    b.ToTable("ViewModelPedido");
                });

            modelBuilder.Entity("pedidos_dap5.Models.ViewModels.ViewModelSoluciones", b =>
                {
                    b.Property<int>("IdSolucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolucion"));

                    b.Property<string>("EstadoDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaInicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaSolucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<string>("Pedido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Solucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TecnicoDescricpcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSolucion");

                    b.ToTable("ViewModelSoluciones");
                });

            modelBuilder.Entity("pedidos_dap5.Models.Pedido", b =>
                {
                    b.HasOne("pedidos_dap5.Models.Estado", "EstadoNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("Estado")
                        .HasConstraintName("FK_Pedidos_Estados");

                    b.HasOne("pedidos_dap5.Models.Tecnico", "TecnicoNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("Tecnico")
                        .HasConstraintName("FK_pedidos_tecnicos");

                    b.HasOne("pedidos_dap5.Models.Usuario", "UsuarioNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("Usuario")
                        .IsRequired()
                        .HasConstraintName("FK_pedidos_usuarios");

                    b.Navigation("EstadoNavigation");

                    b.Navigation("TecnicoNavigation");

                    b.Navigation("UsuarioNavigation");
                });

            modelBuilder.Entity("pedidos_dap5.Models.Solucione", b =>
                {
                    b.HasOne("pedidos_dap5.Models.Pedido", "IdpedidoNavigation")
                        .WithMany("Soluciones")
                        .HasForeignKey("Idpedido")
                        .IsRequired()
                        .HasConstraintName("FK_soluciones_pedidos");

                    b.HasOne("pedidos_dap5.Models.Tecnico", "TecnicoNavigation")
                        .WithMany("Soluciones")
                        .HasForeignKey("Tecnico")
                        .HasConstraintName("FK_Soluciones_Tecnico");

                    b.Navigation("IdpedidoNavigation");

                    b.Navigation("TecnicoNavigation");
                });

            modelBuilder.Entity("pedidos_dap5.Models.Usuario", b =>
                {
                    b.HasOne("pedidos_dap5.Models.Grado", "GradoNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("Grado")
                        .HasConstraintName("FK_Usuarios_Grados");

                    b.Navigation("GradoNavigation");
                });

            modelBuilder.Entity("pedidos_dap5.Models.Estado", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("pedidos_dap5.Models.Grado", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("pedidos_dap5.Models.Pedido", b =>
                {
                    b.Navigation("Soluciones");
                });

            modelBuilder.Entity("pedidos_dap5.Models.Tecnico", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("Soluciones");
                });

            modelBuilder.Entity("pedidos_dap5.Models.Usuario", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
